src/blog/urls.py
from django.conf.urls import url

from . import views
from .feeds import LatestPostsFeed

urlpatterns = [
    # name="blog_list" -> name of the URL to be used in HTML templates
    url(r'^$', views.post_list, name="post_list"),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<slug>[-\w]+)/$',
        views.post_detail, name='post_detail'),
    url(r'^(?P<post_id>\d+)/share/', views.post_share, name="post_share"),

    # we'll use the same 'views.post_list' but with additional "tag_slug" argument
    url(r'^tag/(?P<tag_slug>\w+)$', views.post_list, name="post_list_by_tag"),
    
    # an example using a view class
    url(r'^feed/$', LatestPostsFeed(), name="post_feed"),

    url(r'^search/$', views.post_search, name="post_search"),
]

src/blogsite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # include the Blog views
    # setting the 'namespace' will make all the named views be
    # prefixed with the 'blog' prefix - so so instance - 'blog:post_list'
    url(r'^blog/', include('blog.urls', namespace='blog')),

    # the sitemap url
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
]

src/blog/models.py
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')

    def from_rumen(self):
        return self.get_queryset().filter(author__username='rumen')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published')
    )

    class Meta:
        ordering = ('-published',)

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='published')
    author = models.ForeignKey(User, related_name='blog_posts')
    body = models.TextField()
    published = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=10, choices=STATUS_CHOICES, default='draft')

    # if we add a custom query Manager and want to use the default
    # Post.objects.all().filter()... one we have to add it explicitly
    # It's goot to keep this the first registered Manager as
    # it's used as default in multiple other places
    objects = models.Manager()

    # create a custom query Manager,
    # thus we can use Post.status_published.all().filter()....
    # Also we can use Post.status_published.from_rumen()
    status_published = PublishedManager()

    # add the taggit manager, so now we can use Post.tags.all() (which is as if Tag.objects.all())
    # or for a specific Post - post.tags.all(), post.tags.add('music', 'sports')
    tags = TaggableManager()

    def __str__(self):
        return self.title

    # a convention method
    def get_absolute_url(self):
        # url is set to be:
        # url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<slug>[-\w]+)/$',
        #          views.post_detail, name='post_detail')
        # under the 'blog' namespace
        # so to reverse it we have to set 4 parameters
        return reverse('blog:post_detail', args=[self.published.year,
                                                 self.published.strftime('%m'),
                                                 self.published.strftime('%d'),
                                                 self.slug])


class Comment(models.Model):
    class Meta:
        ordering = ('created',)

    # 1. related_name 'comments' means that we can use
    # post.comments.all() - e.g a named related manager
    # if don't name it Django will implicitly set it to: 'comment_set', so
    # post.comment_set.all()
    # 2. related_query_name 'comment' means we can use it in filter fields like so
    # Post.objects.filter(comment__active=True). If not set it uses the 'related_name'
    post = models.ForeignKey(Post, related_name='comments',
                             related_query_name='comment')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return 'Comment by {} on "{}"'.format(self.name, self.post)

src/blog/forms.py
from django import forms
from .models import Comment


# a form on it's own
class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(max_length=250,
                               required=False,
                               widget=forms.Textarea)


# a form specifically for a model (in this case Comment)
class CommentForm(forms.ModelForm):
    class Meta:
        # specify the assofiated model
        model = Comment
        # specify which fields to use only - if not specified will use all
        fields = ('name', 'email', 'body')


# a form for the search fuctionality
class SearchForm(forms.Form):
    query = forms.CharField(max_length=250)

src/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail
from django.db.models import Count
from taggit.models import Tag
from haystack.query import SearchQuerySet
from .models import Post
from .forms import EmailPostForm, CommentForm, SearchForm


def post_list(request, tag_slug=None):
    posts_all = Post.status_published.all()

    # if this is a tlist for all post tagged with given tag
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        posts_all = posts_all.filter(tags__in=[tag])

    # add pagination - 3 posts per page
    paginator = Paginator(posts_all, 3)
    # get requested page number
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # if page is not an integer then deliver the FIRST page
        posts = paginator.page(1)
    except EmptyPage:
        # if page is out of range then deliver the LAST page
        posts = paginator.page(paginator.num_pages)

    return render(request, 'blog/post/list.html', {'posts': posts,
                                                   'page': page,
                                                   'tag': tag})


def post_detail(request, year, month, day, slug):
    post = get_object_or_404(Post, status='published', slug=slug,
                             published__year=year,
                             published__month=month,
                             published__day=day)

    # get the cmments for this post
    comments = post.comments.filter(active=True)

    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            # create a Comment object from the form BUT DON'T SAVE it to the database yet
            new_comment = comment_form.save(commit=False)
            # assign the Post associated with this Comment
            new_comment.post = post
            # save/commit to the database now
            new_comment.save()
    else:
        comment_form = CommentForm()

    # whether or not a comment was saved
    new_comment_saved = 'new_comment' in locals()

    # Get list with "similar" posts
    post_tags_id = post.tags.values_list('id', flat=True)
    similar_posts = Post.status_published.filter(tags__in=post_tags_id). \
        exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')). \
        order_by('-same_tags', '-published')[:4]

    return render(request, 'blog/post/detail.html', {'post': post,
                                                     'comments': comments,
                                                     'comment_form': comment_form,
                                                     'new_comment_saved': new_comment_saved,
                                                     'similar_posts': similar_posts})


def post_share(request, post_id):
    # retrieve the specified post
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':
        # so this is when form is submitted (on POST)
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # so the form is valid

            # clean the form's data
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())

            subject = '{} ({}) recommends you reading "{}"'.format(cd['name'],
                                                                   cd['email'],
                                                                   post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(post.title,
                                                                     post_url,
                                                                     cd['name'],
                                                                     cd['comments'])
            # real sending of the email
            send_mail(subject, message, 'admin@blogsite.com', [cd['to']])

            sent = True
    else:
        # this is when form is to be displayed (on GET)
        form = EmailPostForm()

    return render(request, 'blog/post/share.html', {'form': form,
                                                    'post': post,
                                                    'sent': sent})


def post_search(request):
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            cd = form.cleaned_data
            query = cd['query']
            results = SearchQuerySet().models(Post).filter(text=query).load_all()

            # count total results
            total_results = results.count()

            return render(request, 'blog/post/search.html', {'form': form,
                                                             'query': query,
                                                             'results': results,
                                                             'total_results': total_results})

    form = SearchForm()
    return render(request, 'blog/post/search.html', {'form': form, })

src/blog/templates/blog/post/_latest_posts.html
{% include "./_posts.html" with posts=latest_posts header='Latest posts' %}

src/blog/templates/blog/post/_posts.html
{% if header %}
    <h3>{{ header }}</h3>
{% endif %}

<ul>
    {% for post in posts %}
        <li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
    {% endfor %}
</ul>

src/blog/templates/blog/post/_tags.html
<p class="tags">
    Tags:
    <!-- {{ tags|join:", "}} -->
    {% for tag in tags %}
        <a href="{% url 'blog:post_list_by_tag' tag.slug %}">{{ tag.name }}</a>
        {% if not forloop.last %}, {% endif %}
    {% endfor %}
</p>

src/blog/templates/blog/post/detail.html
{% extends "../_layout.html" %}

{% load blog_tags %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="date">Published {{ post.published }} by {{ post.author }}</p>
    {{ post.body|markdown }}

    {% include "./_tags.html" with tags=post.tags.all %}

    <h2>Similar posts</h2>
    {% for post in similar_posts %}
        <p><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></p>
    {% empty %}
        There are no similar posts    
    {% endfor %}
 
    <p><a href="{% url "blog:post_share" post.id%}">Share this post</a></p>

    {% with comments.count as comments_count %}
        <h2>{{ comments_count }} comment{{ comments_count|pluralize }}</h2>
    {% endwith %}

    {% for comment in comments %}
        <div class="comment">
            <p class="info">Comment {{ fooloop.counter }} by {{ comment.name }} {{ comment.created }}</p>
            {{ comment.body|linebreaks }}
            
        </div>
    {% empty %}
        <p>There are no comments yet</p>
    {% endfor %}


    {% if new_comment %}
        <h2>Your comment has been added.</h2>
    {% else %}
        <h2>Add a new comment</h2>
        <form action="." method="post">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="Add comment"></p>
        </form>
    {%  endif %}

{% endblock %}

src/blog/templates/blog/post/list.html
{% extends "../_layout.html" %}

{% load blog_tags %}

{% block title %}Posts{% endblock %}

{% block content %}
    <h1>Posts</h1>


    {% if tag %}
        <h2>Posts tagged with "{{ tag.name }}"</h2>
    {% endif %}

    {% for post in posts %}

        <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
        <p class="date">Published {{ post.published }} by {{ post.author }}</p>
        {{ post.body|markdown|truncatewords_html:30 }}

        {% include "./_tags.html" with tags=post.tags.all %}

    {% endfor %}
    
    <!--  pass the posts as the 'page' object for '_pagination.html' -->
    {% include "../_pagination.html" with page=posts %}
    
{% endblock %}

src/blog/templates/blog/post/search.html
{% extends "../_layout.html" %}

{% block title %}Search{% endblock %}

{% block content %}
    {% if "query" in request.GET %}
        <h1>Posts containing "{{ query }}"</h1>
        <h3>Found {{ total_results }} result{{ total_results|pluralize }}</h3>
        {% for result in results %}
        	{% with post=result.object %}
        		<h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
                {{ post.body|truncatewords:5 }}
        	{% endwith %}
        {% empty %}
        	<p>There are no results for your query.</p>
        {% endfor %}
        <p><a href="{% url "blog:post_search" %}">Search again</a></p>
    {% else %}
        <h1>Search for posts</h1>
        <form action="." method="get">
            {{ form.as_p }}
            <input type="submit" value="Search">
        </form>
    {% endif %}
{% endblock %}

src/blog/templates/blog/post/share.html
{% extends "../_layout.html" %}

{% block title %}Share a post{% endblock %}

{% block content %}
    {% if sent %}
        <h1>E-mail successfully sent</h1>
        <p>"{{ post.title }}" was successfully sent by e-mail.</p>
    {% else %}
        <h1>Share "{{ post.title }}" by e-mail</h1>
        <form action="." method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Send e-mail">
        </form>
    {% endif %}
{% endblock %}